# Generated by Django 5.0.4 on 2024-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('capacidad', models.IntegerField()),
                ('equipo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=20)),
                ('partidos_jugados', models.IntegerField()),
                ('partidos_ganados', models.IntegerField()),
                ('partidos_perdidos', models.IntegerField()),
                ('partidos_empatados', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('asistencias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('posicion', models.CharField(max_length=20)),
                ('numero_camiseta', models.IntegerField()),
            ],
        ),
    ]
